### ISSUE TITLE
allow to set a custom logging function in the settings

### ISSUE THREAD

**Issue by sghsri** [Chakroun-Anas/turbo-console-log#107]
Hi! 
I love this extension and have been using it for a while! However, it would be very helpful if we could specify a custom logging function to be used instead of console.log in the settings.

for example, say I have a custom logging function logger.info
I would like to trigger this extension on a variable x and have it print out logger.info("className -> potato -> x", x).

It would be also extremely helpful if this was added!

**Comment by Matrosskin** [comment]
I also prefer using of different logging function, so that feature would be awesome.

**Comment by ShadowGamer3** [comment]
Great idea! I've got a custom logging function that both logs to the console and to a log file, and the ability to call that function and log all that useful data like file, function, and line number so quickly would make this extension 10x more useful!  Sure, the default would be "console.log" but please give users the ability to set custom logging functions.
