### ISSUE TITLE
Custom `console.log` snippet

### ISSUE THREAD

**Issue by fabiospampinato** [Chakroun-Anas/turbo-console-log#11]
It would be nice if this extension had support for a custom `console.log` snippet, for instance this extension might currently produce the following:

```javascript
console.log('myFunction -> myVar', myVar);
```

Some people might like it written in a different style, like:

```javascript
console.log ( 'myFunction → myVar', myVar )
```

Support for this might be added in the form of a `template` setting, where custom tokens gets substituted in, for instance the default template might be:

```javascript
console.log('[wrapper] -> [variable]', [variable]);
```

So that one could add this setting to his configuration:

```json
"turboConsoleLog.template": "console.log ( '[wrapper] → [variable]', [variable] )"
```

This would also enable some advanced features, for instance I could have this template:

```javascript
debug ( '[wrapper]', '[variable]', [variable] ); 
```

And the following function defined somewhere else in my code:

```javascript
function debug ( wrapper, valueName, value ) {
  console.log ( `${wrapper} → ${valueName}`, value );
  if ( isError ( value ) ) debugger;
}
```

What do you think?

**Comment by Chakroun-Anas** [comment]
Hello, 

The customisation in term of style is interesting and  when it comes to content it's even more interesting, i think this feature is definitely a must in the extension.

I will work on it in the weekend,  so basically if everything goes fine it will be implemented by next Monday. 

Thank you very much, i really appreciate your elegant suggestions.

**Comment by fabiospampinato** [comment]
I'm glad you like them! And thank you for being very reactive in implementing all this 😄 

I see a few problems with my proposal though:

1. If there's no wrapper the template will become `console.log ( ' → foo', foo )`.
   - Maybe if there's no wrapper the extension could provide one anyway, something like `global` maybe, in order to have `console.log ( 'global → foo', foo )`
   - Or maybe there could be multiple templates, one for each case, but I think it would be better to avoid this if possible.
2. How do we detect the code written by this extension?
   - Maybe the default template could have the zero-width character embedded in it, and we could have a new setting which defines the regex used to match the lines of code added by this extension. So that if we modify the template we can also modify the regex. But this seems a bit too complicated, and we'll have to instruct the users about the zero-width char trick, this would be an advanced feature though, so maybe the added complexity is ok.

**Comment by almarto** [comment]
> Hello,
> 
> The customisation in term of style is interesting and when it comes to content it's even more interesting, i think this feature is definitely a must in the extension.
> 
> I will work on it in the weekend, so basically if everything goes fine it will be implemented by next Monday.
> 
> Thank you very much, i really appreciate your elegant suggestions.

That weekend wasn't successful :trollface:

I was ready to open a new issue but it'd have been duplicated with this one, I'm facing the problem of my eslint config doesn't like the `console.log` so I'd need either a way to set a setting flag `hey add eslint-disble-line to the end` or this templating setting which is more powerful.

I'd like to know why didn't you finally implemented it if it was because of a lack of time or because you faced any problem which makes the feature impossible to be implemented.

I was thinking to give it a try so would be nice if it's even possible beforehand.

thanks @Chakroun-Anas

**Comment by johnrix** [comment]
Was about to log a request when I found this one logged by @fabiospampinato.

One note I would add (in case there is ever any chance of this getting finished), is that separate templates would be needed for each supported language ie. JS, PHP etc.

**Comment by PaulMEdwards** [comment]
This would be beneficial to us as we use a custom logger and want to use `logger.debug` instead of `console.log`.
