### ISSUE TITLE
not able to log anything

### ISSUE THREAD

**Issue by ermarkar** [Chakroun-Anas/turbo-console-log#119]
ON click of Ctrl + Alt + Del, it prints : (under the colon, a semi-colon) instead of logging the variable.

I have checked my keyboard binding as well.

Re installed and re  started the vs code as well.

any solution?

**Comment by HaiOliver** [comment]
same issue for me, u just need to change another key combination.It will work. For me, I changed Ctr + Shift + /

**Comment by ImanMahmoudinasab** [comment]
Same thing for me, looks like an app is capturing the shortcut so that vs code doesn't receive the pressed keys. I changed the shortcut for now to alt + L and will try to find the app.
