### ISSUE TITLE
Delete all turboed console log messages from every file

### ISSUE THREAD

**Issue by mariomui-viscira** [Chakroun-Anas/turbo-console-log#124]
Is there a way to remove the turboed console.log files globally?

**Comment by demedos** [comment]
What do you mean? The library doesn't keep track of your logs, it's just a shorthand way to call the `console.log` function, like you would do manually.

If you have an open document then you could press `Cmd + Shift + D` to delete the messages, but that would work only for the file you're working on.

To delete them globally you could use just find and replace to bulk replace the `console.log.*$` lines with a blank one, just google that.
