### ISSUE TITLE
Feature request: logMessageSuffix

### ISSUE THREAD

**Issue by mariaedwards** [Chakroun-Anas/turbo-console-log#128]
Could you please add a new property logMessageSuffix and default it to `:`?
So when console.log is added it will be 
```
🟣 ~ file: app.js ~ line 6 ~ second: Second file
```
instead of:
```
🟣 ~ file: app.js ~ line 6 ~ second Second file
```

**Comment by tfreitas90** [comment]
This would be nice....

**Comment by besnikkorca** [comment]
Added [PR](https://github.com/Chakroun-Anas/turbo-console-log/pull/179) that should allow this @mariaedwards @tfreitas90

**Comment by farhadh** [comment]
Hey!

I have added the [PR](https://github.com/Chakroun-Anas/turbo-console-log/pull/190) for this feature for the most recent refactored code :)

I hope @Chakroun-Anas would confirm and merge it <3. I too would like to have this feature so badly :)

**Comment by Chakroun-Anas** [comment]
Hello Farhad,

Thank you for your contribution, did check that all the tests pass ? ^^

Cordially,
________________________________
De : Farhad H. P. Shirvan ***@***.***>
Envoyé : samedi 21 janvier 2023 15:21
À : Chakroun-Anas/turbo-console-log ***@***.***>
Cc : Chakroun Anas ***@***.***>; Mention ***@***.***>
Objet : Re: [Chakroun-Anas/turbo-console-log] Feature request: logMessageSuffix (#128)


Hey!

I have added the PR<https://github.com/Chakroun-Anas/turbo-console-log/pull/190> for this feature for the most recent refactored code :)

I hope @Chakroun-Anas<https://github.com/Chakroun-Anas> would confirm and merge it <3. I too would like to have this feature so badly :)

**Comment by farhadh** [comment]
Hi @Chakroun-Anas!

My pleasure. Yes. All tests, as shown below, were passed for my 3 PRs (#190, #191, and #192) which are on top of each other :)

```Started initializing default profile extensions in extensions installation folder. file:///home/farhad/.vscode/extensions

Completed initializing default profile extensions in extensions installation folder. file:///home/farhad/.vscode/extensions

Loading development extension at /home/farhad/turbo/turbo-console-log



  ✓ Insert log message related to a class constructor param (3636ms)

  ✓ Insert log message related to a class function param (738ms)

  ✓ Insert log message related to a function parameter within a class function (654ms)

  ✓ Insert log message related to a deconstructred property assigned to a variable (977ms)

  ✓ Insert log message related to a multiline function parameter  (2072ms)

  ✓ Insert log message related to a function parameter (546ms)

[main 2023-01-22T16:55:31.807Z] update#setState checking for updates

[main 2023-01-22T16:55:31.908Z] update#setState idle

  ✓ Insert log message in the context of a function with a bunch of decorators (515ms)

  ✓ Determine the closing brace line num (286ms)

  ✓ Insert log message in the last line of the file (451ms)

  ✓ Insert log message related to an object variable (350ms)

  ✓ Insert log message related to an object function call (532ms)

  ✓ Obj function call no variable assignment (287ms)

  ✓ Object variable with a declared type (545ms)

  ✓ Insert log message related to a function (which params are defined in one line) param (312ms)

  ✓ Insert log message related to a primitive variable (402ms)

  ✓ Insert log message related to a variable declared in a promise callback (477ms)

  d

    Single line

      ✓ Assigned to a variable

      ✓ Parameter of a function

      ✓ Chained call

    Multiple lines

      ✓ Example 01

      ✓ Example 02

      ✓ Example 03

      ✓ Example 04

  Empty functions

    ✓ Example 01

    ✓ Example 02

  Insert log message related to a variable with a function as the value

    ✓ Example 01

    ✓ Example 02

    ✓ Example 03

  JS Line Code Processing

    ✓ Assignment of object literal to a variable

    ✓ Assignment of an array to a variable

    Classes

      ✓ Check class declaration

      ✓ Get class name

    Functions
      ✓ Check built in function invocation

      ✓ Check named function Declaration

      ✓ Get function name

      ✓ Assignment of function to a variable

      ✓ Check object function call

      ✓ Anonymous functions

      ✓ Arugment of anonymous function

      ✓ Should transform anonymous function

[main 2023-01-22T16:55:56.039Z] Extension host with pid 7170 exited with code: 0, signal: null.

Exit code:   0
Done

Waiting for the debugger to disconnect...
Waiting for the debugger to disconnect...

**Comment by Chakroun-Anas** [comment]
Hello Farhad,

Do you have some time to talk this weekend ?

Thx
________________________________
De : Anas Chakroun ***@***.***>
Envoyé : dimanche 22 janvier 2023 16:52
À : Chakroun-Anas/turbo-console-log ***@***.***>
Objet : RE: [Chakroun-Anas/turbo-console-log] Feature request: logMessageSuffix (#128)

Hello Farhad,

Thank you for your contribution, did check that all the tests pass ? ^^

Cordially,
________________________________
De : Farhad H. P. Shirvan ***@***.***>
Envoyé : samedi 21 janvier 2023 15:21
À : Chakroun-Anas/turbo-console-log ***@***.***>
Cc : Chakroun Anas ***@***.***>; Mention ***@***.***>
Objet : Re: [Chakroun-Anas/turbo-console-log] Feature request: logMessageSuffix (#128)


Hey!

I have added the PR<https://github.com/Chakroun-Anas/turbo-console-log/pull/190> for this feature for the most recent refactored code :)

I hope @Chakroun-Anas<https://github.com/Chakroun-Anas> would confirm and merge it <3. I too would like to have this feature so badly :)

**Comment by farhadh** [comment]
Hi @Chakroun-Anas!

Yes. Just let me know when :)

**Comment by Chakroun-Anas** [comment]
Hello,

So sorry, i barely find some time, where are you from i may to ask?

Cordially,
________________________________
De : Farhad H. P. Shirvan ***@***.***>
Envoyé : samedi 28 janvier 2023 11:58
À : Chakroun-Anas/turbo-console-log ***@***.***>
Cc : Chakroun Anas ***@***.***>; Mention ***@***.***>
Objet : Re: [Chakroun-Anas/turbo-console-log] Feature request: logMessageSuffix (#128)


Hi @Chakroun-Anas<https://github.com/Chakroun-Anas>!

Yes. Just let me know when :)

**Comment by farhadh** [comment]
It's ok, @Chakroun-Anas. Why though? :)) You can see it in my profile ;)

**Comment by Chakroun-Anas** [comment]
Hello,

What do you think about creating a slack channel for the extension so that we can communicate more efficiently, i need to talk to you before getting to collaborate please ^^

Thx
________________________________
De : Farhad H. P. Shirvan ***@***.***>
Envoyé : mardi 31 janvier 2023 12:10
À : Chakroun-Anas/turbo-console-log ***@***.***>
Cc : Chakroun Anas ***@***.***>; Mention ***@***.***>
Objet : Re: [Chakroun-Anas/turbo-console-log] Feature request: logMessageSuffix (#128)


It's ok, @Chakroun-Anas<https://github.com/Chakroun-Anas>. Why though? :)) You can see it in my profile ;)

**Comment by farhadh** [comment]
@Chakroun-Anas OK. Would you mind creating the Slack channel and letting me know about it? :)

**Comment by Chakroun-Anas** [comment]
Hello,

I created the channel 🙂

I need your email so that i can invite you and get back to work 😉

Thx,
________________________________
De : Farhad H. P. Shirvan ***@***.***>
Envoyé : vendredi 3 février 2023 11:34
À : Chakroun-Anas/turbo-console-log ***@***.***>
Cc : Chakroun Anas ***@***.***>; Mention ***@***.***>
Objet : Re: [Chakroun-Anas/turbo-console-log] Feature request: logMessageSuffix (#128)


@Chakroun-Anas<https://github.com/Chakroun-Anas> OK. Would you mind creating the Slack channel and letting me know about it? :)

**Comment by farhadh** [comment]
@Chakroun-Anas I sent you and email :)

**Comment by Chakroun-Anas** [comment]
Hello guys,

Done by @farhadh , thank you so much for your efforts ^^
