### ISSUE TITLE
Clickable file:line_number output format!

### ISSUE THREAD

**Issue by MaximeEvangeliste** [Chakroun-Anas/turbo-console-log#130]
I don't know if there is currently a way to do this but I thought it would make it even more turbo.

Currently the format when I log something is this:
```js
console.log('🚀 ~ file: file.js ~ line 10 ~ variable, variable);
```

It would be awesome if the file + line number was displayed as this:
```js
console.log('🚀 ~ file.js:10 ~ variable, variable);
```

Since it's a standard you can just ctrl+click the file:line_number and it will take you directly to it!

**Comment by Chakroun-Anas** [comment]
Included starting from `v2.6.1`, see #184 , thx.
