### ISSUE TITLE
Comment, Uncomment, Delete doesn't work - v2.1.6

### ISSUE THREAD

**Issue by jussaurabh** [Chakroun-Anas/turbo-console-log#131]
The log message is working fine but comment, uncomment and delete do not.

**Comment by NNSTH** [comment]
Facing the same after upgrade, any idea of how to fix it? otherwise this extension might become not usable for me

**Comment by niktor76** [comment]
Same here, would be great to have these functions.

**Comment by pachiraDIG** [comment]
+ 1

**Comment by SteffenEnz** [comment]
plus 1

**Comment by heiway** [comment]
macOS Monterey
vscode arm64
v2.1.7

same issue

**Comment by niktor76** [comment]
Same here, commenting and deleting doesn't work.
Someone know an alternative extension?
