### ISSUE TITLE
Option to output Console.warn

### ISSUE THREAD

**Issue by demedos** [Chakroun-Anas/turbo-console-log#137]
Hi,

it would be nice to have an option to add another keybinding to print console.warn instead of console.log.
This would be especially useful when working with React Native, since many times displaying the message on a screen warning is just quicker than checking the debugger.

Thanks!

**Comment by ShadowGamer3** [comment]
#107 is an issue similar to this.  Both are great ideas though, and setting another keybind to a separate log function, whether that be console.warn or a custom function would be very helpful!

**Comment by jofftiquez** [comment]
> #107 is an issue similar to this. Both are great ideas though, and setting another keybind to a separate log function, whether that be console.warn or a custom function would be very helpful!

Doesn't have to be a new keybind, as long as it's customizable.

**Comment by jofftiquez** [comment]
Apparently there's a PR for this -> https://github.com/Chakroun-Anas/turbo-console-log/pull/155

**Comment by demedos** [comment]
> > #107 is an issue similar to this. Both are great ideas though, and setting another keybind to a separate log function, whether that be console.warn or a custom function would be very helpful!
> 
> Doesn't have to be a new keybind, as long as it's customizable.

Having different keybindings would allow us to use different console functions rather that only the one specified in the settings

**Comment by jofftiquez** [comment]
> > > #107 is an issue similar to this. Both are great ideas though, and setting another keybind to a separate log function, whether that be console.warn or a custom function would be very helpful!
> > 
> > 
> > Doesn't have to be a new keybind, as long as it's customizable.
> 
> Having different keybindings would allow us to use different console functions rather that only the one specified in the settings; nonetheless this is a good starting point

I see, I understand. Altho that's a totally different (new) issue.

**Comment by Chakroun-Anas** [comment]
Hello guys,

Sorry for my inactivity in the last couple of months, as they say better late than never, i just published version 2.2.0 that includes both `logType` & `logFunction` properties:

- logType: Same exact in [#155](https://github.com/Chakroun-Anas/turbo-console-log/pull/155)
- logFunction: A custom log function that can be specified by you

When logFunction is specified, logType is ignored.

Thank you so much for contributing to my humble work, i love you ❤️

**Comment by jofftiquez** [comment]
Thank you @Chakroun-Anas 🎊
