### ISSUE TITLE
want postfix 

### ISSUE THREAD

**Issue by 253eosam** [Chakroun-Anas/turbo-console-log#143]
I wish I could put the last delimiter in the log message.

ex) console.log('[🐱 DDD] | file: index.js | line 10 | str **(HERE)**', str)

**Comment by shakil-shahan** [comment]
> I wish I could put the last delimiter in the log message.
> 
> ex) console.log('[cat DDD] | file: index.js | line 10 | str **(HERE)**', str)

@Chakroun-Anas Please make it happen

**Comment by besnikkorca** [comment]
Added a [PR](https://github.com/Chakroun-Anas/turbo-console-log/pull/179) for postfix.

**Comment by farhadh** [comment]
Here you are #190

**Comment by IdreesSamadi** [comment]
any progress on #190?

**Comment by farhadh** [comment]
@IdreesSamadi I'm awaiting @Chakroun-Anas :)

**Comment by Chakroun-Anas** [comment]
Done, thx @farhadh ^^
