### ISSUE TITLE
[Feature request] - Customize the end message

### ISSUE THREAD

**Issue by MariuzM** [Chakroun-Anas/turbo-console-log#144]
Could the end message be customized? 

For example from
`console.log("🚀 ~ authAPI", authAPI);`

To:
`console.log("🚀 ~ authAPI -", authAPI);`

For me i just want to add ` -` to the end of the message.

**Comment by alexvrv** [comment]
I would really love this feature. I was actually looking for it but I guess is not implemented yet...

**Comment by StereoKiss** [comment]
i implemented it. You can see it here, but it isnt pullt: https://github.com/Chakroun-Anas/turbo-console-log/pull/186

**Comment by farhadh** [comment]
I have PR #190 for this by which you can also set the variable in the extension's settings. Also, I have fixed the variable's line number.

@StereoKiss I'm afraid you have put the delimiter outside of the quotation mark.

**Comment by StereoKiss** [comment]
i cant resolve it. Can you do it?

**Comment by farhadh** [comment]
@StereoKiss yes, it's done in #190 :)
