### ISSUE TITLE
An extra console.log

### ISSUE THREAD

**Issue by GuetarniWalid** [Chakroun-Anas/turbo-console-log#146]
With the last release (2.1.7) in VSCode, when i use the wrapped log message i have on extra consol.log().

Example: 
```
  test.only('ExchangeSpotAction.fetchAllOpenOrderIn', async (assert) => {
    const orders = await ftxAdapter.fetchAllOpenOrderIn()
    console.log('🚀 ------------------')
    console.log('🚀 ~ orders', orders)
    console.log('🚀 ------------------')
    console.log('🚀 ~ orders', orders)
  })
```

There is  a solution to fix this probleme ?

**Comment by SliverYuki** [comment]
not resolve yet, I have to disabled the `Wrap log Message`, now it show single line, but no wrapper
![image](https://user-images.githubusercontent.com/19161689/144033806-2ee963d5-9cc6-49f8-91fd-d1af308d6ed7.png)

![image](https://user-images.githubusercontent.com/19161689/144033758-d3dac79b-9797-4e36-a191-46dfe503fdbb.png)

**Comment by Chakroun-Anas** [comment]
Hello guys, i just pushed a new version `v2.2.1` that fix this, can you please check and get back to me so that we can close this issue ? thx.

**Comment by GuetarniWalid** [comment]
Thank you so much, it is all good.

**Comment by SliverYuki** [comment]
> Hello guys, i just pushed a new version `v2.2.1` that fix this, can you please check and get back to me so that we can close this issue ? thx.

Thanks, now it works perfect.
