### ISSUE TITLE
How can I use shortcuts on my MacOS machine?

### ISSUE THREAD

**Issue by TangoPJ** [Chakroun-Anas/turbo-console-log#159]

**Comment by sarunmrzn** [comment]
Please add shortcuts to mac aswell

**Comment by Chakroun-Anas** [comment]
The default shortcut to insert a log message is `ctrl + alt + L`, when it comes to MacBook the alt key transform to the option key, so the shortcut to use when on MacBook is `ctrl + option + L`.
