### ISSUE TITLE
Add an Open Source License to the Project

### ISSUE THREAD

**Issue by manuth** [Chakroun-Anas/turbo-console-log#160]
Hello, Turbo Console Log Team
The current version of this extension currently doesn't have an opensource license (a `LICENSE`-file in the root of this repo).
Thus, this extension isn't able to be published to [Eclipse's Open Source Extension Marketplace ovsx](https://open-vsx.org/) on its own.

Websites like [Choose A License](https://choosealicense.com/) will help you making a decision.

Could you please add an open source license to this extension and publish a new version?
That would be great!

Thanks for your great work ✨ 😄

**Comment by CWempe** [comment]
Looks like a duplicate of https://github.com/Chakroun-Anas/turbo-console-log/issues/118

**Comment by manuth** [comment]
Oh - it is, thank you very much for letting me know
