### ISSUE TITLE
Doesn't seem to work on Mac with M1 processor

### ISSUE THREAD

**Issue by iAmHarmon** [Chakroun-Anas/turbo-console-log#162]
### System info:
**Processor:** M1
**OS:** MacOS Monterey 12.3.1

### VSCode Info
Version: 1.66.0
Commit: e18005f0f1b33c29e81d732535d8c0e47cafb0b5
Date: 2022-03-30T05:49:37.118Z (6 days ago)
Electron: 17.2.0
Chromium: 98.0.4758.109
Node.js: 16.13.0
V8: 9.8.177.11-electron.0
OS: Darwin arm64 21.4.0

### Problem
I am unable to generate console logs in Typescript React project. Unable to use keybinding `ctrl+opt(alt)+l`.

### Actual behavior
1. Click on variable to log
2. Press ctrl+opt(alt)+l

### Expected behavior
Variable is logged in the next line

### Thing I've tried
* Reloaded vscode
* Uninstalled and reinstalled extension
* Remapped keybinding to `cmd+ctrl+l`

**Comment by OrhanOzkercin** [comment]
I am facing the same problem

**Comment by grigoryevandrey** [comment]
Same thing :(

**Comment by Chakroun-Anas** [comment]
Hello guys,

I'm unable to reproduce the problem, can you please share with me a minimalistic repository where the problem occurs so that i debug and fix it ? Thx

**Comment by grigoryevandrey** [comment]
I'm sorry, i think i just used it incorrectly. Thank you for the response, issue can be closed i guess
