### ISSUE TITLE
ctr-alt-l not working

### ISSUE THREAD

**Issue by amarch** [Chakroun-Anas/turbo-console-log#167]
Just installed thsi extension in visual code running react code on a windows 11 machine. Instead of generating the console.log line it turns the selected parameter into the ø symbol.
Is there some setting to modify which I am not aware of?

**Comment by abhay-singh-au3** [comment]
> Just installed thsi extension in visual code running react code on a windows 11 machine. Instead of generating the console.log line it turns the selected parameter into the ø symbol. Is there some setting to modify which I am not aware of?

How did you fixed this ?

**Comment by robinhodemorais** [comment]
> Acabei de instalar a extensão thsi no código visual executando o código de reação em uma máquina Windows 11. Em vez de gerar a linha console.log, ela transforma o parâmetro selecionado no símbolo _. Existe alguma configuração para modificar que eu não estou ciente?

poderia falar como fez, pq aqui nãoi funciona
