### ISSUE TITLE
ctrl + alt + l  for windows deleting the selected value

### ISSUE THREAD

**Issue by dhavalveera** [Chakroun-Anas/turbo-console-log#171]
Hello,

I found that your Turbo Console Log VS Code Extension is really helpful for debugging.

but I found that when I select a variable or something for the console.log and do `ctrl` + `alt` + `l` then it's deleting the selected variable or any other value for the console and the first time it shows the console.log but there's no selected value coming in console.log and also it's deleting the selected variable/value and if undo the changes and retry the same command, then no console.log is not coming n only variable or any other selected value is getting deleted

anyone can help me with this?

**Comment by RakeshPotnuru** [comment]
@dhavalveera 
I'm also having the same issue. It has something to do with windows keyboard config. I just changed the key bindings for this extension (`CTRL` + `ALT` + `T`).

**Comment by dhavalveera** [comment]
> @dhavalveera I'm also having the same issue. It has something to do with windows keyboard config. I just changed the key bindings for this extension (`CTRL` + `ALT` + `T`).

how you change the key binding for this extension? @RakeshPotnuru

**Comment by RakeshPotnuru** [comment]
Preferences -> Keyboard shortcuts -> There you can search for the extension and change shortcut
