### ISSUE TITLE
Delete all console logs function doesn't delete wrapped logs

### ISSUE THREAD

**Issue by AlanJereb** [Chakroun-Anas/turbo-console-log#177]
#### Issue description
The wrapped console.log doesn't remove properly if using delete all console logs hotkey. 

#### Steps to reproduce the issue

1.  In extension settings enable setting: Turbo Console Log: Wrap Log Message
2. Select part of your code and add console.log by pressing Ctrl + Alt + L 

> ```
> console.log("🚀 -----------🚀");
> console.log("🚀 ~ foo", foo);
> console.log("🚀 -----------🚀");
> ```

3. Delete all console.logs by pressing Shift + Alt + D

#### What's the expected result?
All console logs, including wrapped logs, should be deleted.

#### What's the actual result?
Only the main console log gets deleted. Wrapped logs remain.
```
console.log("🚀 -----------🚀");
console.log("🚀 -----------🚀");
```

**Comment by Chakroun-Anas** [comment]
Hello, 

Not relevant any more anymore, tested with version `v2.8.0`, thank you for reporting the issue.
