### ISSUE TITLE
[BUG] Not working if there's no line break and other issues

### ISSUE THREAD

**Issue by angelhdzmultimedia** [Chakroun-Anas/turbo-console-log#180]
Hello, congratulations for this amazing extension.

I was blown away with this extension when someone recommended it (or an extension pack, can't remember).

I found 2 bugs so far.

**1.** If the line I want to create logs for doesn't have a line break in next line, I get a:
![image](https://user-images.githubusercontent.com/10191085/193981842-3757523f-acf5-43c1-9b87-bd4796cc2294.png)

And if there's a line of code before it that has a line break, the log for the desired line is appended in top of it and below the previous one like this:

![image](https://user-images.githubusercontent.com/10191085/193983249-0e23b011-b534-4a91-9162-2ea49312c27e.png)

Even if I add a semi-colon at the end of the line.

**2.** Doesn't work on objects properties (or is just a non-implemented feature?)

### Final Words
Eager to see these things fixed, other than that, thank you!
Programming is gonna be easier and faster now!

**Comment by Chakroun-Anas** [comment]
Hello @angelhdzmultimedia, 

Thank you for your kind words regarding my humble work i really appreciate it 👍

I just published a new version `v2.5.2` that deal with the first bug that you mentioned, can you please share with me  a code snippet that illustrates the second bug so that we can tackle it 😉 ? 

Thank you again.

**Comment by angelhdzmultimedia** [comment]
> Hello @angelhdzmultimedia,
> 
> Thank you for your kind words regarding my humble work i really appreciate it 👍
> 
> I just published a new version `v2.5.2` that deal with the first bug that you mentioned, can you please share with me a code snippet that illustrates the second bug so that we can tackle it 😉 ?
> 
> Thank you again.



```
const user = {
  email: "TheEmail@Thedomain.com",
  name: "TheName,
}
```

Clicking on email would result in:
```
const user = {
  email: "TheEmail@Thedomain.com",
  name: "TheName,
}
console.log(user.email);
```

**Comment by Chakroun-Anas** [comment]
Hello @angelhdzmultimedia,

I hope you are fine and doing well, as they say better late than never, i just pushed a new version `v2.7.4` that deal with logging an object property the right way, which means if the variable subject of the log message is in the scope of an object then the log message will take in consideration the object also (exactly the way you described in the previous comment), will appreciate your feedback, thank you so much and sorry for the late response.

Thx

**Comment by Chakroun-Anas** [comment]
Hello, i noticed another issue with the decorators detection after publishing `v2.7.4`, thanks to the snippet `email: "TheEmail@Thedomain.com"` that you shared in your last message :P, `v2.7.5` should be live and dealing well with your example and hopefully any object property logging, thank you so much again ^^

**Comment by angelhdzmultimedia** [comment]
> Hello @angelhdzmultimedia,
> 
> I hope you are fine and doing well, as they say better late than never, i just pushed a new version `v2.7.4` that deal with logging an object property the right way, which means if the variable subject of the log message is in the scope of an object then the log message will take in consideration the object also (exactly the way you described in the previous comment), will appreciate your feedback, thank you so much and sorry for the late response.
> 
> Thx

So warm and kind words! Thank you for allowing me to contribute. 🔥🤝

Definitely I will check the update and will leave feedback.

I'm glad that these issues are being addressed because this is an amazing extension.

I'll will get back to you shortly. 

Wishing you health, peace, and success.

**Comment by angelhdzmultimedia** [comment]
### Update

🤯 Wow!!! Everything works now! All isues gone, and I can now log object literals properties!!!

What an amazing job! Thank you! 🎉🔥🤝👏
