### ISSUE TITLE
command 'turboConsoleLog.displayLogMessage' not found

### ISSUE THREAD

**Issue by Jveen-D** [Chakroun-Anas/turbo-console-log#182]
vscode  version: 1.72.2 (user setup)
`Ctrl`+`Alt`+`L` => 'command 'turboConsoleLog.displayLogMessage' not found'
![image](https://user-images.githubusercontent.com/46897216/196078908-af10097c-216a-4b87-abc0-268f69b36765.png)

**Comment by ghun131** [comment]
I get the same error message and tried the solutions here https://github.com/Chakroun-Anas/turbo-console-log/issues/35

**Comment by roojay520** [comment]
I have same err

**Comment by ghun131** [comment]
I revert my plugin back to `2.5.1` and things are back to normal

**Comment by JJunYang** [comment]
I get same error

**Comment by Jveen-D** [comment]
> 

This is effective，tks.

**Comment by Jveen-D** [comment]
> I revert my plugin back to `2.5.1` and things are back to normal

This is effective，tks.

**Comment by BindingOx** [comment]
> I revert my plugin back to `2.5.1` and things are back to normal

how do you do this?

**Comment by huytranorient** [comment]
> 

Thanks! :)

**Comment by huytranorient** [comment]
@ghun131 , Thanks! :)

**Comment by Aimer-Fan** [comment]
thanks, click here to install another version.
![image](https://user-images.githubusercontent.com/47803845/196106510-b36399b3-0dde-4874-96a3-34405eb4188a.png)

**Comment by pankaj-yadav0507** [comment]
> I revert my plugin back to `2.5.1` and things are back to normal

Worked for me.

**Comment by michael-chan-mox** [comment]
> I revert my plugin back to `2.5.1` and things are back to normal

Downgraded to `2.5.3` also worked for me.

**Comment by michael-chan-mox** [comment]
> I revert my plugin back to `2.5.1` and things are back to normal

Downgraded to `2.5.3` also worked for me.

**Comment by mygitstyle** [comment]
+1

**Comment by Chakroun-Anas** [comment]
Hello guys, 

I just pushed a new version `v2.5.3` yesterday without manually testing ( should be automated by the way ), went to sleep than wakeup to this 😅

Anyway i just pushed a new version `v2.5.4` that fix all this miss, thank you to try and give me your feedback 🙂

**Comment by Chakroun-Anas** [comment]
The main reason we got this problem is linked to trying bundling the extension using `esbuild` so that the final bundle is smaller leading to a faster download experience, this was a failure with `v2.5.3` but i think we got it right with `v2.5.5`,can you confirm that this is the case so that we can close this issue ? Thx 😁
