### ISSUE TITLE
[feature] Changelog for VS Code

### ISSUE THREAD

**Issue by cpecorari** [Chakroun-Anas/turbo-console-log#183]
Hi, thanks for this amazingly helpful extension for VS Code !

Since i installed it i've already had few updates, but unfortunately Changelog is not updated at release time, so that when VSCode asks for reload we can not have a quick look at the Changelog tab :
![Capture d’écran 2022-10-19 à 15 14 59](https://user-images.githubusercontent.com/56672657/196701328-32d48915-9a08-487e-8659-74538281c8e0.png)

Ref: https://github.com/Chakroun-Anas/turbo-console-log/blob/9f74a8eb7569fa3d03f72894e15f51fc55e1c6df/CHANGELOG.md

Would you mind filling it so that it would become much more fluid ? :)

Thanks a lot

**Comment by Chakroun-Anas** [comment]
Hello @cpecorari , 

Thank you so much for your feedback, promise i will keep an eye on this starting from version `v2.9.0` 😊
