### ISSUE TITLE
change the ` ~ line 17` part to `:17: so it can be accessed

### ISSUE THREAD

**Issue by rattkin** [Chakroun-Anas/turbo-console-log#184]
Please change the line format from
```
🚀 ~ file: foo.tsx ~ line 170
```
to something VSCode recognizes and can go to directly, like:
```
🚀 ~ file: foo.tsx:170
```
this string can be copied to clipboard and put into `ctrl+g` dialog

**Comment by rattkin** [comment]
ok so it's done allready https://github.com/Chakroun-Anas/turbo-console-log/pull/140

Does it need more work?

**Comment by Chakroun-Anas** [comment]
Integrated in version `2.6.1`, can you check and confirm please @rattkin ? Thx

**Comment by rattkin** [comment]
works, thank you!
