### ISSUE TITLE
custom prefix

### ISSUE THREAD

**Issue by geddski** [Chakroun-Anas/turbo-console-log#19]
cool extension! The only part I don't love is the `TCL: ` prefix. I'd prefer to change mine to `-` or something less distracting. Could you make the prefix accept a user setting?

**Comment by Chakroun-Anas** [comment]
Hello,

I agree with you, it will be better to have the possibility to change the prefix.

I will work on that very soon.

Thx.

**Comment by geddski** [comment]
sweet!

**Comment by Chakroun-Anas** [comment]
Hello,

You can now determine your own prefix by changing logMessagePrefix in settings.json.

Enjoy.

**Comment by geddski** [comment]
works like a charm, thank you!
