### ISSUE TITLE
Cmd + alt + l on a MAC don't work for me

### ISSUE THREAD

**Issue by thearabbit** [Chakroun-Anas/turbo-console-log#2]
`Cmd + alt + l` on a MAC don't work for me.
I tried `Cmd + shift + l` it work, but override of multiple select of VS code

**Comment by Chakroun-Anas** [comment]
Hello, 

I'm sorry i just forgot to update the README file, the right command is ctrl + shift + l in windows/linux or cmd + shift + l on a MAC as you mentioned. 

The README file is updated.

Thx.

**Comment by thearabbit** [comment]
Thanks for your reply, but `cmd+shift+l` is duplicate with

![image](https://user-images.githubusercontent.com/4495160/37403940-f4dd7e6c-27c2-11e8-855b-51511dd35d94.png)

**Comment by Chakroun-Anas** [comment]
Hello, 

I made a huge change, the command to insert a log message is ctrl + alt + l either on windows/linux or a mac.

Thx

**Comment by Chakroun-Anas** [comment]
For the moment (v1.2.5) The right way to insert the log message is to select the variable and then press ctrl + alt + l in all the platforms: windows, linux and mac.

This issue will be closed.

Thx.

**Comment by thearabbit** [comment]
👍

**Comment by leotm** [comment]
Just to clarify on Mac as I at first misread l as 'i' and was trying command...
`ctrl + alt/option + l` works.

**Comment by tronicroger** [comment]
On linux Mint: Ctrl + Alt + i || L || 1 all don't work, but Ctrl + Alt + L does lock out my desktop. 
How can I change the keymap on this??

**Comment by jayad23** [comment]
control + option + L
