### ISSUE TITLE
Ctr + Alt + I is Wrong on Mac

### ISSUE THREAD

**Issue by NextZeus** [Chakroun-Anas/turbo-console-log#20]
Ctr + option(Alt)  + L is correct. not I , but L.

**Comment by Chakroun-Anas** [comment]
Hello,

Both ctrl+alt+l and ctrl+alt+L are working !

**Comment by epilande** [comment]
@Chakroun-Anas I just ran into this..In the docs the l looks like a capital i. 😂 

IlIl
