### ISSUE TITLE
Some shortcuts not working

### ISSUE THREAD

**Issue by scottcall** [Chakroun-Anas/turbo-console-log#201]
Hello, I'm excited I found this extension for vscode, thank you to all those who have contributed to its creation! I have noticed one issue - that the shortcuts for commenting, uncommenting, and deleting the logs that were created by Turbo Console are not working on my Win10 laptop. I'm running the latest version of vscode, and the latest of Turbo Console (v2.7.1), and I've tried changing the shortcuts to those functions (with non-conflicting shortcuts) with no success. I've also reverted to several earlier versions of Turbo Console (back to v2.5) with no change. Fortunately the main shortcut Ctrl + Alt + L is working just fine, so at least I have the main functionality.

Is anyone else experiencing this issue or may know of a fix?

**Comment by Chakroun-Anas** [comment]
Hello @scottcall,

Indeed commenting, uncommenting and deleting needs to be heavily checked again, the main focus last month was on the main shortcut (inserting the log message with the right context and specially the right line), will check this soon and make it more robust again;)

Have a great weekend!
