### ISSUE TITLE
Shortcut is not working for single comma.

### ISSUE THREAD

**Issue by tanzim077** [Chakroun-Anas/turbo-console-log#202]
Without "ctrl + alt+ L" no other shortcut is working when the log message is converted into a single comma.     

console.log("🚀 ~ file: annotation.service.js:182 ~ videosId", videosId);  **// Every shortcut is working here**

console.log('🚀 ~ file: annotation.service.js:182 ~ videosId', videosId);  **// Not working here**

**Comment by Chakroun-Anas** [comment]
Hello @tanzim077 , 

Not relevant anymore, tested with version `v2.8.0`, thank you for reporting the issue.
