### ISSUE TITLE
Comment, uncomment, and delete not working when "Turbo Console Log: Log Message Suffix" is on.

### ISSUE THREAD

**Issue by WebDevMirza** [Chakroun-Anas/turbo-console-log#204]
Hi, 

### Comment, Uncomment, and Delete not working

I found a bug. When I apply "**Turbo Console Log: Log Message Suffix**", comment, delete, and uncomment shortcut do not work properly. Although it **works perfectly without setting any** "Turbo Console Log: Log Message Suffix".

**Thank you.**

**Comment by Chakroun-Anas** [comment]
Hello, 

Thank you for reporting the issue, would please see my comment on issue #203 and give me your feedback since it's related ?

Thx.
