### ISSUE TITLE
The extension don't appear for install in linux

### ISSUE THREAD

**Issue by jandro5** [Chakroun-Anas/turbo-console-log#209]
I have a debian 10

**Comment by ngdevnilesh** [comment]
For debian os console.log is not appearing

**Comment by curtisbelt** [comment]
A couple things to try.

- Make sure the keybinding is what you think it is.
- Make sure there isn't another keybinding overlapping.

Instructions:

1. Open Keyboard Shortcuts
2. Search for `turboConsoleLog.displayLogMessage`
3. You should now see the keybinding entry.
4. Right click on the keybinding and click "Show Same Keybindings".

**Comment by jandro5** [comment]
> ve a debian

I found the problem. I am using the vscodium and the extensión dont appear in repository.
