### ISSUE TITLE
Option to remove semicolon

### ISSUE THREAD

**Issue by Julien76** [Chakroun-Anas/turbo-console-log#21]
Hi,

I'm using your extension and I love it.

Would it be possible to have an option to enable/disable semicolon at the end of the console log?
When using with prettier, it always return a warning.

Thanks

**Comment by Chakroun-Anas** [comment]
Hello,

I have just published an update that give you the ability to insert or not a semicolon in the end of the log message.

All you need to do is to toggle addSemicolonInTheEnd property in settings.json.

**Comment by Julien76** [comment]
Hi,
thanks for this.
