### ISSUE TITLE
[BUG?] Problem with variable with "function call with arrow function argument" as value

### ISSUE THREAD

**Issue by angelhdzmultimedia** [Chakroun-Anas/turbo-console-log#210]
### Expected Behavior
Clicking the variable `user`
`const user = users.find(item => item.email === email)`
Should add a log in the next line.

### Actual Behavior
The arrow function gets expanded, and the log is inserted inside its body.
A workaround is to select the variable along with the empty space next to it.

https://user-images.githubusercontent.com/10191085/231728103-f43c2f85-58c5-4967-9834-2b99daf16b2d.mp4

**Comment by Chakroun-Anas** [comment]
Hello, 

Thank you for reporting the issue, will check this soon and get back to you.

**Comment by Chakroun-Anas** [comment]
Hello,

I just pushed a new version `v2.9.2` that deals with this, would you please test it and get back to me so that we can close this issue? 

Thx.

**Comment by angelhdzmultimedia** [comment]
### You are on fire! 🔥🤯🤝👏🎉

It works good. Thank you. This extension really improves DX and saves us time!

Next week I'm going to take some time to deliberatedly play with it to find more possible bugs and report them.
