### ISSUE TITLE
[FEATURE REQUEST] Deep Object

### ISSUE THREAD

**Issue by angelhdzmultimedia** [Chakroun-Anas/turbo-console-log#211]
**You have been working a lot, so please take this as Low Priority.**

I noticed that in an object literal, it only works with the first level properties.

```ts
const user = {
  data: {
    name: 'asd'
  }
}
console.log("🚀 ~ file: login.post.ts:44 ~ user.data:", user.data)
```

```ts
const user = {
  data: {
    name: 'asd'
  }
    console.log("🚀 ~ file: login.post.ts:43 ~ name:", name) // ERROR: "," expected.
}
```

### Idea
If this is complicate to implement, then I suggest detecting if the variable is an object and wrap it between `JSON.stringify()` to log all properties altogether instead:

```ts
const user = {
  data: {
    name: 'asd',
  }
}
console.log("🚀 ~ file: login.post.ts:44 ~ user:", JSON.stringify(user))

```

### Amazing job! 🔥🤯🤝

**Comment by Chakroun-Anas** [comment]
Hello @angelhdzmultimedia,

Thank you very much for your very valuable contributions and your kind words ❤️, i had this in mind once i pushed the version that deals with logging a one level object property, very nice catch from you  😉.

This should be a very nice little challenge, will deal with it ASAP no worries 💪

Greetings

**Comment by Chakroun-Anas** [comment]
Hello @angelhdzmultimedia,

Version `v2.9.3` is live in the store handling this issue well hopefully 🥳, as usual thank you in advance to check again so that we close this one and move to others. 

PS: It was fun to implement 😁

Greetings

**Comment by angelhdzmultimedia** [comment]
![image](https://user-images.githubusercontent.com/10191085/232193607-e17b3e1f-1ff8-4b52-9eb3-af4355f0b33f.png)

![image](https://user-images.githubusercontent.com/10191085/232193645-a879a10f-b7eb-40cf-8dc3-ddd7e318b849.png)

😂😍🔥🤝🎉 Let's get ready for **Turboooooo**!!! 
Greetings.
