### ISSUE TITLE
快捷键冲突

### ISSUE THREAD

**Issue by myaijarvis** [Chakroun-Anas/turbo-console-log#215]
该插件的快捷键：ctrl + alt + L （Windows）
与IntelliJ IDEA Keybindings插件冲突
能否自定义快捷键？

**Comment by ding-js** [comment]
![image](https://github.com/Chakroun-Anas/turbo-console-log/assets/14885918/8013e13e-1c5b-40e5-9218-dcc7bd25b9db)

![image](https://github.com/Chakroun-Anas/turbo-console-log/assets/14885918/357887f5-c889-4119-b182-92b2003f56c1)

you can customize your keyboard shortcuts

**Comment by ding-js** [comment]
@Chakroun-Anas Hello, you can close this issue, this is just an shortcut conflict
