### ISSUE TITLE
how could I change log style

### ISSUE THREAD

**Issue by yuwanlin** [Chakroun-Anas/turbo-console-log#24]
turbo-console-log is awesome!
when I log, the content is always wrapped by double quote. How could I change it to single quote? in setting.json? I can't find some configuration.

**Comment by diegolmello** [comment]
Yeah, it would be awesome!

**Comment by seanwhudson** [comment]
same thing with tab/space usage. tslint complains, and blocks the build, if double quotes and tab spacing is mixed with spaces. This extension uses tabs and double quotes, both which violate my (and many others I suspect) linting rules. Needs to be configurable or it's unusable!

**Comment by astone2014** [comment]
I agree this should be a feature. Otherwise people who use linters may spend so much time fixing the quotes that it's not worth using the extension.

**Comment by adamk33n3r** [comment]
I thought it was odd that in the gifs on the marketplace it showed single quotes. I'm having the same problem with double quotes and tabs. We use single quotes and spaces so the linter complains.

**Comment by Chakroun-Anas** [comment]
This issue is linked to : [`[FEATURE_REQUEST] To add option to use single quote`]( https://github.com/Chakroun-Anas/turbo-console-log/issues/30 ).
