### ISSUE TITLE
VUE files error: Irregular whitespace not allowed

### ISSUE THREAD

**Issue by Julien76** [Chakroun-Anas/turbo-console-log#26]
Hi,

Since last update (1.2.11) it does not work with vue file:

I am getting the following error:
```http://eslint.org/docs/rules/no-irregular-whitespace  Irregular whitespace not allowed  ```

for a console.log as follow:
```console.log("​save -> this.close()", this.close())```

Deleting the *save* (the first word in that instance, remove the error). The workaround seems a bit random. But the issue is always there in .vue file.

I think that this is different issue than #17 

Any idea?

Thanks

**Comment by Chakroun-Anas** [comment]
Hello,

In order to distinguish the log messages inserted by the extension, the zero-width space (\u200b) is inserted in the beginning of each one of them. 

So in your example the zero-width space is inserted just before the word save, hence the reason the problem is gone when you deleted the whole word tho only the character before s is causing the problem.

I will check further and get back to you soon.

Thx.

**Comment by Julien76** [comment]
That makes sense. Thanks for the explanation.
Is there any way to revert back to the hold behaviour through an option?
I kind of liked the prefix "TCL: " :)

**Comment by Chakroun-Anas** [comment]
Hello,

Initially the application didn't had the prefix, it was introduced to better identify the log messages; i guess if we can achieve this objective without any distraction it would be even better.

I liked the prefix too 💔😃

**Comment by bryanjenningz** [comment]
I liked the TCL prefix because it allowed me to filter my logs for the string "TCL" so only the TCL logs would show up, so it was really useful for debugging.

**Comment by Chakroun-Anas** [comment]
Hello,

The prefix is back with the ability to specify a custom one by changing the logMessagePrefix property.

This issue should be resolved, please give me your feedback so that i can close it.

Thx.

**Comment by Julien76** [comment]
Hi,
Thanks a lot for the update.
It works great. The issue can be closed :+1:
