### ISSUE TITLE
Cmd+D shouldn't be enforced

### ISSUE THREAD

**Issue by fabiospampinato** [Chakroun-Anas/turbo-console-log#3]
By default `cmd+d` maps to `editor.action.addSelectionToNextFindMatch`, which is something I, and probably many others, use pretty frequently.

I had to put:

`{ "key": "cmd+d", "command": "-extension.deleteAllLogMessages" }`

in my `keybindings.json` in order to remove this.

I don't think this shortcut should be provided by default.

**Comment by Chakroun-Anas** [comment]
Hello, 

I agree with you, the command key will change to cmd + alt + d to avoid the conflict.

I will apply this changes a few hours from now.

Thank you very much.

**Comment by Chakroun-Anas** [comment]
The command to delete log messages is changed to: Ctrl + Alt + d on all platforms: linux, windows and mac.
