### ISSUE TITLE
Should obey tab settings in the editor

### ISSUE THREAD

**Issue by JasonCubic** [Chakroun-Anas/turbo-console-log#32]
my editor is set to use 2 spaces for the tab.  turbo console log inserts a real tab.
![image](https://user-images.githubusercontent.com/8921015/51270478-df52e600-1979-11e9-8327-ed9e68ce1244.png)

**Comment by adrigm** [comment]
Same for me. Angular works with spaces.

**Comment by gabrielsclimaco** [comment]
+1

**Comment by Chakroun-Anas** [comment]
Duplicate of #59
