### ISSUE TITLE
Linting rules

### ISSUE THREAD

**Issue by drugoi** [Chakroun-Anas/turbo-console-log#33]
It's not an issue, but please — add your own linter rules, because it hard to contribute to your project (all your code rules by internal linters of contributors). 
Hope's you fix it fast.

Also, great extension and good job.

**Comment by Chakroun-Anas** [comment]
Hello,

Linting rules are added to the project.

Thank you very much for your feedback.

**Comment by drugoi** [comment]
Thank you!
