### ISSUE TITLE
Not working but why?

### ISSUE THREAD

**Issue by Hearen** [Chakroun-Anas/turbo-console-log#35]
Sorry to open this issue but it seems it's not working in *Visual Studio Code 1.30.1* in Ubuntu 16.04. 

F.Y.I

- working on an angular project;
- using vim in VSCode;
- disabling vim and reloading won't help;
- restarting the VSCode won't help;

**Comment by Chakroun-Anas** [comment]
Hello,

I will check that and get back to you soon.

Sorry for the inconvenience.

**Comment by ashwell** [comment]
I just installed this extension but it doesn't appear to be working. I'm guessing it is related to the vim keymap. On OSX `ctrl + cmd + L` does nothing and attempting to call the commands from the command palette doesn't work either.

**Comment by qmmr** [comment]
@ashwell Just installed it on my Mac OSX 10.13.6, VSC 1.42.0 and it works. The shortcut is: ```Ctrl + Option + L``` Hope this helps 👍

**Comment by suyogkh** [comment]
Please check either your pc is using `ctrl + alt + L` shortcut in prior.
I have changed mine to 
```
 {
    "key": "ctrl+shift+2",
    "command": "turboConsoleLog.displayLogMessage"
  },
  {
    "key": "ctrl+shift+3",
    "command": "turboConsoleLog.deleteAllLogMessages"
  },
  {
    "key": "ctrl+shift+4",
    "command": "turboConsoleLog.commentAllLogMessages"
  },
  {
    "key": "ctrl+shift+6",
    "command": "turboConsoleLog.uncommentAllLogMessages"
  },
```
Preferences -> keyboard shortcut -> change it to json format -> search turbo and replace with this

**Comment by ermarkar** [comment]
i dont know what happend, but when i use the shortcut, sometimes it works, sometimes it shows/prints ,

**Comment by lanxuexing** [comment]
@suyogkh @ermarkar @qmmr Works perfectly on Mac OSX! 😆 

- commentAllLogMessages
⇧ + ⌥ + C
- deleteAllLogMessages
⇧ + ⌥ + D
- displayLogMessage
⌃ + ⌥ + L
- uncommentAllLogMessages
⇧ + ⌥ + U

```
{
  "key": "shift+alt+c",
  "command": "turboConsoleLog.commentAllLogMessages"
}
{
  "key": "shift+alt+d",
  "command": "turboConsoleLog.deleteAllLogMessages"
}
{
  "key": "ctrl+alt+l",
  "command": "turboConsoleLog.displayLogMessage"
}
{
  "key": "shift+alt+u",
  "command": "turboConsoleLog.uncommentAllLogMessages"
}
```

**Comment by gsivaprabu** [comment]
> Please check either your pc is using `ctrl + alt + L` shortcut in prior. I have changed mine to
> 
> ```
>  {
>     "key": "ctrl+shift+2",
>     "command": "turboConsoleLog.displayLogMessage"
>   },
>   {
>     "key": "ctrl+shift+3",
>     "command": "turboConsoleLog.deleteAllLogMessages"
>   },
>   {
>     "key": "ctrl+shift+4",
>     "command": "turboConsoleLog.commentAllLogMessages"
>   },
>   {
>     "key": "ctrl+shift+6",
>     "command": "turboConsoleLog.uncommentAllLogMessages"
>   },
> ```
> 
> Preferences -> keyboard shortcut -> change it to json format -> search turbo and replace with this



In windows after the above change working fine

/C:/Users/**username**/AppData/Roaming/Code/User/keybindings.json

![image](https://user-images.githubusercontent.com/2444608/144974860-773d8405-4cda-4027-8829-464dad02ae5a.png)

**Comment by Jacobify** [comment]
![image](https://user-images.githubusercontent.com/39615077/196085132-e42144e0-2e0a-48c5-908b-71012b030a51.png)

Hi there, Right after updating the extension it stopped working , i tried everything above yet still it does not work.

**Comment by hungtd97** [comment]
@Jacobify Same for me, looking for a solution

**Comment by thisisirfan** [comment]
> ![image](https://user-images.githubusercontent.com/39615077/196085132-e42144e0-2e0a-48c5-908b-71012b030a51.png)
> 
> Hi there, Right after updating the extension it stopped working , i tried everything above yet still it does not work.

I have downgraded to make work, waiting for the patch fix

**Comment by niravjadatiya** [comment]
facing same issue 
![image](https://user-images.githubusercontent.com/25176031/196093320-186598bc-eeff-4e73-aeb1-50391e467751.png)
command 'turboConsoleLog.displayLogMessage' not found

**Comment by harryHoangX** [comment]
command 'turboConsoleLog.displayLogMessage' not found

**Comment by longld-0832** [comment]
same here, after update new version "command 'turboConsoleLog.displayLogMessage' not found"

**Comment by cola639** [comment]
same here, after update new version "command 'turboConsoleLog.displayLogMessage' not found"

**Comment by niravjadatiya** [comment]
I found workaround
![image](https://user-images.githubusercontent.com/25176031/196110025-ebd9a069-a51c-44d9-b60c-5c922e2036fc.png)

select 2.5.1 and then reload vscode
its working for me

**Comment by scottcall** [comment]
Hello, I'm excited I found this extension for vscode, thank you to all those who have contributed to its creation! I have noticed one issue - that the shortcuts for commenting, uncommenting, and deleting the logs that were created by Turbo Console are not working on my Win10 laptop. I'm running the latest version of vscode, and the latest of Turbo Console (v2.7.1), and I've tried changing the shortcuts to those functions (with non-conflicting shortcuts) with no success. I've also reverted to several earlier versions of Turbo Console (back to v2.5) with no change. Fortunately the main shortcut Ctrl + Alt + L is working just fine, so at least I have the main functionality.

Is anyone else experiencing this issue or may know of a fix?

**Comment by avitanthetaa** [comment]
Add this code to the file in view > command palette > Open Keyboard Shortcuts (json). 

[
  {
    "key": "ctrl+alt+2",
    "command": "turboConsoleLog.displayLogMessage"
  }
]

It will then work if you press ''ctrl+alt+2''.

**Comment by avitanthetaa** [comment]
> Hello,
> 
> This is not relevant anymore with the latest version `v2.9.3`, thank you.

You can try this version v2.5.1, It works for me

**Comment by akib1997** [comment]
Using 2.9.6 but still not working. Updated json already.
