### ISSUE TITLE
How do you configure this to include a prefix on variable selection ?

### ISSUE THREAD

**Issue by thopper** [Chakroun-Anas/turbo-console-log#36]
I'm doing alot of angular dev work, using typescript. 
When selecting the variable in vscode, would it be possible to include the prefix :
this.

ex:
	// console.clear();
		this.module = this.modForm.value.module;
		console.log('​GearTeethCalculatorComponent -> calcMODPitchDiameter -> module', module);

**Comment by Chakroun-Anas** [comment]
Hello,

Just select this.module instead of module and the inserted log message will be:

console.log('​GearTeethCalculatorComponent -> calcMODPitchDiameter -> this.module', this.module);
