### ISSUE TITLE
Not working with VS Code version 1.30.2

### ISSUE THREAD

**Issue by mvesign** [Chakroun-Anas/turbo-console-log#37]
Installed extension and reloaded VS Code, but shortcode of a new console log is not working. Option is present in the command palette of VS Code, but nothing happens when the option is selected.
![turbo-command-palette-vscode](https://user-images.githubusercontent.com/9944224/51823128-bec24e80-22de-11e9-829b-89e32c90de78.jpg)

Current setup:
- VS Code 1.30.2
- Node.js 8.9.3
- Windows_NT ia32 10.0.17763

**Comment by Chakroun-Anas** [comment]
Hello,

I will check and get back to you soon.

Thx.

**Comment by Chakroun-Anas** [comment]
Hello,

I have just tested the extension with respect to the setup that you mentioned and it's working just fine !

One question please, did you select a variable before executing the command ctrl + alt + L ?

If there is no variable selected nothing will happen, as mentioned in the description you should select a variable that is the subject of the debugging before executing the command !

Thx.

**Comment by kurienkoa** [comment]
hello, 
VSCode 1.30.2
windows 10
turbo console works only in moment selected variables and lose focus in index.js

**Comment by Nxt3** [comment]
On 1.31.0-insiders I can't comment out all logs or delete all logs by either the command palette or keyboard shortcuts.

**Comment by mvesign** [comment]
Hello,

Thanks for the quick reply, and sorry for the lack of replying back in a quick matter.

Tried it again today, and with success. Don't know what caused it to not work in the first place. But it seems to be resolved now.

Steps I took today:
- Select the variable by double clicking on it.
- Execute the command CTRL + ALT + L
- And voila... Received a nice log line below the selected variable.

So will close this issue.

**Comment by M0hammedImran** [comment]
it is not working for me aswell

**Comment by tantrarahul** [comment]
> It is not working for me as well.
> When I try to select the variable and press CTRL + ALT + L it replaces the variable with ' l̥ '.
> Please help.

Facing Same issue

**Comment by Yulms** [comment]
I had the same problem. It consisted in the fact that the same key combination was used by another extension - "bookmarks" in my case

**Comment by alfianandinugraha** [comment]
make sure your shortcut ( CTRL + ALT + L ) is just for Turbo Console Log
![image](https://user-images.githubusercontent.com/34809276/75969021-e089fe00-5f00-11ea-9136-91f1039f8443.png)

**Comment by sastaachar** [comment]
Setup : 
windows
vscode on wsl

The shortcut was not working for me as well , it was placing l̥ instead, 
but changing the shortcut key binding solved the issue for me , 
I changed it to  ( CTRL + ALT + K )

It looks like  ( CTRL + ALT + some keys ) will print the alternate characters like ā æ ē r̥ ñ ū ī ō l̥ .

**Comment by chiragbytes** [comment]
Hello @alfianandinugraha, How to open that key bindings settings can you please inform me?

**Comment by M0hammedImran** [comment]
> Hello @alfianandinugraha, How to open that key bindings settings can you please inform me?

CRTL + K S

**Comment by Abhishekbhard** [comment]
> Setup :
> windows
> vscode on wsl
> 
> The shortcut was not working for me as well , it was placing l̥ instead,
> but changing the shortcut key binding solved the issue for me ,
> I changed it to ( CTRL + ALT + K )
> 
> It looks like ( CTRL + ALT + some keys ) will print the alternate characters like ā æ ē r̥ ñ ū ī ō l̥ .
Thank you so much Your solution worked for me

**Comment by ShrihariMohan** [comment]
![image](https://user-images.githubusercontent.com/60439461/169009313-5efc3cf8-ae61-4843-a332-4db7212d349e.png)
 Since all the commands are SHIFT + ALT combination , I just added SHIFT + ALT + L as command !
