### ISSUE TITLE
Forgot to change the namespace of the commands

### ISSUE THREAD

**Issue by fabiospampinato** [Chakroun-Anas/turbo-console-log#4]
This extension provides 2 commands, `extension.displayLogMessage` and `extension.deleteAllLogMessages`.

You shouldn't prefix those commands with `extension`, the prefix should be `turboConsoleLog` or something like that.

Basically `extension.displayLogMessage` should be renamed to `turboConsoleLog.displayLogMessage`.

**Comment by Chakroun-Anas** [comment]
Hello, 

I agree with you, i just forgot to do that :P

I will apply this change a few hours from now.

Thx.

**Comment by Chakroun-Anas** [comment]
The namespace is changed from extension which is the default one to turboConsoleLog.

Thx.
