### ISSUE TITLE
[Feature Request] Option to disable prefix

### ISSUE THREAD

**Issue by Nxt3** [Chakroun-Anas/turbo-console-log#40]
Setting `"logMessagePrefix": ""`  doesn't remove the prefix. I don't want any prefix and there doesn't seem to be a way to disable them; i.e. no colon.

**Comment by Chakroun-Anas** [comment]
Hello, 

The prefix is used to detect the log messages inserted by the extension in order to perform the following actions: Comment the log messages, uncomment and delete them.

The prefix is also useful when it comes to filter the logs so that you keep just the messages inserted by the extension.

As an alternative, you can set the prefix to something less distracting: ~ for example !

**Comment by NitinHsharma** [comment]
Hey @Chakroun-Anas 

Did the changes for optional prefix, using comments.
added the pull request for the same. Please check and let me know if anything need to be change.

Pull request number  #43

**Comment by Chakroun-Anas** [comment]
Hello @NitinHsharma,

I really appreciate your contribution and for that i thank you so much, the concern with the comment solution is that it's easily breakable by editing the comment or delete it, if so then the detection will not work anymore and as a consequence all the other functionalities relying on it will fail too. 

I prefer to keep the current implementation and as i said before you can always set the prefix to something less distracting !

**Comment by NitinHsharma** [comment]
Hey @Chakroun-Anas 
Thank you so much for writing me back.
The above implementation works only in case of a blank prefix, although I agree with your thought of the consequence of failing stuff.

Will surely think about it and will try to come up with something.

**Comment by NitinHsharma** [comment]
What about, project name (directory name).
And this will use only in case if prefix is null or can give toggle button in configuration for prefix or project name. 


Please suggest your thought, so that I can start working on the same :)
