### ISSUE TITLE
Not working properly in multi line variables

### ISSUE THREAD

**Issue by PJijin** [Chakroun-Anas/turbo-console-log#41]
const details = {

         title: res.data.title,

         type: res.data.location_type
      
         }; 

When i select details and try to console log using Ctrl + ALT + L

       const details = {
  
       console.log('TCL: App -> componentDidMount -> details', details)
  
       title: res.data.title, 
  
       type: res.data.location_type      
       };

**Comment by Chakroun-Anas** [comment]
Hello,

This behavior is a must, i ensure you that i will on it in the coming days.

Thank you for your feedback.

**Comment by Chakroun-Anas** [comment]
Hello,

I have pushed a new version that deals with the following multiline variables: 

1) Object
2) Variable getting it's value from single function invocation or nested functions invocations
3)Template string

Can you please test it and give me your feedback.

**Comment by PJijin** [comment]
@Chakroun-Anas  Works fine now 🥳
