### ISSUE TITLE
Ambigius guideline

### ISSUE THREAD

**Issue by cr4zyc4t** [Chakroun-Anas/turbo-console-log#42]
It's take me more than an hour to figure out why I cannot use this plugin by pressing:
```ctrl + alt + i```
I know it's my mistake but please update guideline shortcut keys to "Ctrl + Alt + L" 😄

**Comment by Chakroun-Anas** [comment]
Hello,

I'm really sorry for the inconvenience, the README is updated so that an L is used instead of l.

Thank you.
