### ISSUE TITLE
[Feature Request] console.debug

### ISSUE THREAD

**Issue by blickwerker** [Chakroun-Anas/turbo-console-log#44]
I would like to see an option to change the output from console.log(...) to console.debug(...). Cheers!

**Comment by NitinHsharma** [comment]
I did the change in the existing code to support above feature,
Please check the pull request #45.
Feel free to check and give review points, Will surely do the necessary changes if required.

**Comment by kb-ig** [comment]
What ever happened to this request? I can see that the PR had some activity - force push branch then closed PR - but it doesnt look like the functionality exists, and it's not mentioned in the readme 🤔

I'd love to be able to be able to use debug logs instead of regular logs.

**Comment by NitinHsharma** [comment]
Hey just saw some activity so couldn't stop myself to redo the thing with updated code.
Please check #155 pull request for different types of log options.

**Comment by Chakroun-Anas** [comment]
Done
