### ISSUE TITLE
Turbo Console Log doesn't work if the variable being used is on the last line in the file

### ISSUE THREAD

**Issue by amandatennent** [Chakroun-Anas/turbo-console-log#46]
When trying to use Turbo Console Log to output console lines for a selected variable, if that variable is on the final line of the fileTurbo Console Log doesn't output the console line at all. It should insert a new line at the end of the file and place the console line there.

**Comment by Chakroun-Anas** [comment]
Not relevant with the latest version `v2.5.1`
