### ISSUE TITLE
This doesn't work anymore 

### ISSUE THREAD

**Issue by abhagsain** [Chakroun-Anas/turbo-console-log#49]
When I press the default shortcut it writes ī then I changed the shortcut to Ctrl + Alt + O. It worked for a while now it's not working at all.

**Comment by Chakroun-Anas** [comment]
Hello,

I can't reproduce the scenario that you are describing so please give me the full details in order to reproduce otherwise i can't help you.

Thank you.

**Comment by abhagsain** [comment]
I don't know what is the issue but when I press the keyboard shortcut you've set it writes this ō letter!

**Comment by Chakroun-Anas** [comment]
Hello,

You can always change the default shortcut to another shortcut, check the following article:

https://code.visualstudio.com/docs/getstarted/keybindings
