### ISSUE TITLE
Commands contributed to the command palette should be prefixed with the extension name

### ISSUE THREAD

**Issue by fabiospampinato** [Chakroun-Anas/turbo-console-log#5]
You should rename the provided commands:

```
Display Log Message => Turbo Console: Display Log
Delete All Log Messages => Turbo Console: Delete All Logs
```

Other than this being a common practice, I couldn't find those commands in the command palette because I was searching for "Turbo" or "Console"

**Comment by Chakroun-Anas** [comment]
Hello, 

Again you got me :P, i will apply this change a few hours from now.

Thx.

**Comment by Chakroun-Anas** [comment]
The requested change is applied.

Thx.
