### ISSUE TITLE
Configuration names should have a common prefix

### ISSUE THREAD

**Issue by SharpSeeEr** [Chakroun-Anas/turbo-console-log#50]
The four settings should have a common prefix added to avoid naming conflicts and allowing easier searching.
Instead of:
```json
{
  "wrapLogMessage": false,
  "logMessagePrefix": "TCL",
  "addSemicolonInTheEnd": false,
  "quote": false
}
```
Add prefix:
```json
{
  "turboConsoleLog.wrapLogMessage": false,
  "turboConsoleLog.logMessagePrefix": "TCL",
  "turboConsoleLog.addSemicolonInTheEnd": false,
  "turboConsoleLog.quote": false
}
```
Or optionally displayed as:
```json
{
  "turboConsoleLog": {
    "wrapLogMessage": false,
    "logMessagePrefix": "TCL",
    "addSemicolonInTheEnd": false,
    "quote": false
  }
}
```

This makes finding and editing the appropriate settings much easier by simply searching for the name of the extension.  Pull request incoming.

**Comment by Chakroun-Anas** [comment]
Hello,

Your PR is merged to master, thank you so much for helping me making this extension better.

Regards.
