### ISSUE TITLE
Unable to produce a log

### ISSUE THREAD

**Issue by TomYeoman** [Chakroun-Anas/turbo-console-log#52]
Hi thanks for developing the extension looks like it would be handy!

I'm unable to get the shortcut working on my windows 10 machine however. I've tried using it on a typescript + JavaScript file with neither of them working

Version : 1.2.0

![image](https://user-images.githubusercontent.com/14075632/54833623-5e380800-4cb6-11e9-8abf-27c5c53a6c73.png)

**Comment by Chakroun-Anas** [comment]
Duplicate of #53
