### ISSUE TITLE
[Feature request] TCL logging without selected text

### ISSUE THREAD

**Issue by cycle4passion** [Chakroun-Anas/turbo-console-log#55]
If nothing selected and not over a word simply add new line

console.log("')

obviously respecting TCL VS code setting for parenthesis type and set the cursor within the quotes.

let word = "Hello"; // cursor lies between 'o' and 'r' of word (nothing selected).

console.log("TCL: word", word);

See existing fork: https://marketplace.visualstudio.com/items?itemName=letrieu.turbo-console-log-fork

**Comment by Chakroun-Anas** [comment]
Not relevant anymore.
