### ISSUE TITLE
Alt + Shift + D doesn't work on MAC

### ISSUE THREAD

**Issue by MR-T77** [Chakroun-Anas/turbo-console-log#56]
Only the combination CTRL+Alt+L works on Mac. The other's (to comment, delete, uncomment, don't work)

**Comment by Chakroun-Anas** [comment]
Hello,

I can't reproduce the issue, so would please give me more hints so that i can help you.

Thanks.

**Comment by MR-T77** [comment]
What type of information would be helpful?

**Comment by charleston-code** [comment]
none of the key bindings work on my mac as well. Is there another way to execute the tasks besides keyboard shortcuts? For instance, by right-clicking? Is there a contextual menu?

**Comment by domiSchenk** [comment]
it may not work because your using backtick?
The method `detectAll` uses following REGEX: 
https://github.com/Chakroun-Anas/turbo-console-log/blob/d704dda9dbc2b93fdf04c7e5a4b8f16ab599175f/log-message.js#L239

so ` are not catched.

should i open a new issue for this?

**Comment by Chakroun-Anas** [comment]
#70

**Comment by Chakroun-Anas** [comment]
Related to #70
