### ISSUE TITLE
FunctionName Not Being Parsed Out in Typescript Files

### ISSUE THREAD

**Issue by WretchedDade** [Chakroun-Anas/turbo-console-log#58]
So as you can see the when generating a console.log for the bar parameter in the following function the functionName -> syntax isn't added automatically. After digging into this I noticed it was because the regular expression used for testing the line for a named function didn't allow for the return type specified by functions in typescript. It would be very useful to use the extension as intended so I went ahead and wrote up a fix for this in pull request #57. 

![code](https://user-images.githubusercontent.com/17183431/57743860-d7d7eb00-7694-11e9-90b9-b9d1309df909.png)

**Comment by Chakroun-Anas** [comment]
Hello,

PR accepted, thank you so much for your efforts.
