### ISSUE TITLE
Use spaces instead of tabs

### ISSUE THREAD

**Issue by Kalaschnik** [Chakroun-Anas/turbo-console-log#59]
ESLint complains, rightly, for the use of tabs instead of spaces:

![image](https://user-images.githubusercontent.com/9831678/57833015-58900780-77b9-11e9-8191-1389c1e69372.png)

**Comment by toddmark** [comment]
![image](https://user-images.githubusercontent.com/5175214/57906976-73907380-78ae-11e9-8bfd-fb8f940a3fa2.png)
I got the same issue.

**Comment by jdpnielsen** [comment]
Yep.. Still waiting on word regarding https://github.com/Chakroun-Anas/turbo-console-log/pull/16

**Comment by Chakroun-Anas** [comment]
Hello Guys, 

I will check this tonight.

Thanks so much.

**Comment by Chakroun-Anas** [comment]
Hello,

I have pushed a new version that deal with this, can you guys test it and give me your feedback.

Thanks.

**Comment by Kalaschnik** [comment]
It works! Thank you!
I’m on VS Code 1.34.0 and TCL 1.2.18
