### ISSUE TITLE
Only the `console.log` calls inserted by this extension should be removed

### ISSUE THREAD

**Issue by fabiospampinato** [Chakroun-Anas/turbo-console-log#6]
If I execute `Delete All Log Messages` on this file:

```js
function main () {
  console.log('...');
  const foo = 1;
  console.log('main -> foo', foo);
}
```

It gets transformed to:

```js
function main () {
  const foo = 1;
}
```

While it should instead become:

```js
function main () {
  console.log('...');
  const foo = 1;
}
```

Basically only the `console.log` calls inserted by this extension should be removed. 

One way of doing this would be to prefix all the strings with '[TS]', or something, and then check if that string is present. This would be pretty ugly though. A smarter way, that I think should work, would be to prefix the strings with one (or more) [zero-width](https://en.wikipedia.org/wiki/Zero-width_space) spaces and then check for those.

**Comment by Chakroun-Anas** [comment]
Hello, 

This is a really interesting feature, i ensure you that it will be taken in account.

Thx.

**Comment by Chakroun-Anas** [comment]
The requested feature is implemented, all the features will be applied to just the log messages that was inserted by the extension, including: deleting, commenting and uncommenting.

Thx.
