### ISSUE TITLE
[Feature request] possibility to disable className/functionName output

### ISSUE THREAD

**Issue by madeinspace** [Chakroun-Anas/turbo-console-log#61]
I love your plugin but ended up disabling it because I found the addition of prefix + className - functionName makes it really difficult to read.

Most of the time I just log the variable name and that's enough.

Could you add perhaps a setting to disable these to just have this: 

console.log("SelectedVariable", SelectedVariable)

Thanks for considering

**Comment by Chakroun-Anas** [comment]
Hello,

I have just  pushed a new version (1.2.25) with the ability to insert or not the enclosing class and function in the log message, basically you just need to set the values of the following booleans: insertEnclosingClass and insertEnclosingFunction.

Here we go !
