### ISSUE TITLE
[Feature Request] ESlint no-console rule

### ISSUE THREAD

**Issue by almarto** [Chakroun-Anas/turbo-console-log#63]
This plugin isn't compatible with the ESlint rule `no-console` so it'd be nice if there is a setting to configure this.

If true, the snippet could have `//eslint-disbale-line` or something like that

**Comment by zthxxx** [comment]
or you can try [**dont-care-log**](https://github.com/zthxxx/dont-care-log) to solve eslint / lint-staged problems
