### ISSUE TITLE
comment,delete,uncomment,doesn't work

### ISSUE THREAD

**Issue by zhouxinnana** [Chakroun-Anas/turbo-console-log#68]
comment,delete,uncomment, doesn't work
![ScreenGif4](https://user-images.githubusercontent.com/17378786/61518906-42165e80-aa3d-11e9-9634-4fea55fa2ea2.gif)

display log message can work
![ScreenGif](https://user-images.githubusercontent.com/17378786/61518474-35453b00-aa3c-11e9-9d81-ad6e30b0a25c.gif)

Turbo Console Log: v1.2.26
VS Code: v1.36.1
SO: Windows 10

**Comment by SimonGolms** [comment]
Look at your keyboard shortcuts mapping. In my case these were already assigned to the Bookmark Extension.

**Comment by Osky772** [comment]
I have same problem. I can log but I can't delete, comment and uncomment.

**Comment by Osky772** [comment]
> Look at your keyboard shortcuts mapping. In my case these were already assigned to the Bookmark Extension.

I tried do it in many ways but I have only one shortcut and it's for this extension.

**Comment by zhouxinnana** [comment]
> Look at your keyboard shortcuts mapping. In my case these were already assigned to the Bookmark Extension.

![image](https://user-images.githubusercontent.com/17378786/62026924-f7e86680-b20e-11e9-8a5c-6e0225879336.png)

update keyboard shortcuts mapping,doesn't work

**Comment by Chakroun-Anas** [comment]
Hello,

In order fix an issue i should be capable to reproduce it and unfortunately this is not the case based on the information you provided. 

For the moment i cannot really help you however i will keep this issue opened ...

**Comment by Chakroun-Anas** [comment]
Hello,

The extension rely on the prefix in order to detect the inserted log messages, i bet that you removed the prefix which obviously messed up the functionality. 

The obvious solution is to force a default prefix, i will work on that soon.

Thx
