### ISSUE TITLE
[Feature Request] Support for alternative log providers i.e. Winston

### ISSUE THREAD

**Issue by D4vx** [Chakroun-Anas/turbo-console-log#69]
Firstly - this extension has made life very easy for quick console logging, for this I thank you :)

I have recently been using Winston as my primary logger and have forked this extension adding the option to replace the basic 'console.log' with whatever custom logger prefix you want, set via the options. 
In addition I have mapped 3 more keys for quick access to debug, warn and error types. This is more of a convenience thing. 
logFunction = 'log' default is 'console' 
ctrl+alt+l = log.info || console.info
ctrl+alt+d = log.debug || console.debug
ctrl+alt+e = log.error || console.error
ctrl+alt+w = log.warn || console.warn

My implementation isnt very slick but im happy to submit a PR if anyone thinks this might be a useful addition - otherwise check out my fork I guess?

**Comment by shekhar7** [comment]
+1

**Comment by deindesignpl** [comment]
It would be actually very useful to have this kind of functionality. All we need is a possibility to define custom replacement for `console.log`, that could be defined by user.

**Comment by RaviPi-Kore** [comment]
+1

**Comment by jofftiquez** [comment]
Look -> https://github.com/Chakroun-Anas/turbo-console-log/pull/155

**Comment by SergioSuarezDev** [comment]
+1
