### ISSUE TITLE
Looking for a contributor?

### ISSUE THREAD

**Issue by fabiospampinato** [Chakroun-Anas/turbo-console-log#7]
I'm probably going to keep this extension installed, but it's currently not exactly how I'd like it to be, for instance see my issues: https://github.com/Chakroun-Anas/turbo-console-log/issues/3 https://github.com/Chakroun-Anas/turbo-console-log/issues/4 https://github.com/Chakroun-Anas/turbo-console-log/issues/5 https://github.com/Chakroun-Anas/turbo-console-log/issues/6.

I can submit a few PRs for those issues I've opened, do you want me to do this?

**Comment by Chakroun-Anas** [comment]
Hello,

The issues #3 and #4 and #5 are pretty simple to fix, however the feature mentioned in #6 needs a little bit of work.

After few hours from now i will consacre two hours to work into the project and i think they will be enough to fix all these issues.

Thank you very much @fabiospampinato i really appreciate your collaboration.

**Comment by fabiospampinato** [comment]
No problem, thank you for this extension :)
