### ISSUE TITLE
Delete all console log not work on Macbook Pro

### ISSUE THREAD

**Issue by pookdeveloper** [Chakroun-Anas/turbo-console-log#70]
Delete all console log not work on Macbook Pro
Link with a video:
https://www.loom.com/share/33d3e4643a764e02943a902d9aa0c7f8

**Comment by Chakroun-Anas** [comment]
Hello,

Is comment and uncomment log messages functionalities working ? 

Thx

**Comment by pookdeveloper** [comment]
Hello @Chakroun-Anas the comment and uncomment dosen't work 
Thanks

**Comment by Chakroun-Anas** [comment]
Hello @pookdeveloper, 

The detection of the log messages is failing !, please share with me the prefix that you set for the log messages (spaces included ).

Thx.

**Comment by pookdeveloper** [comment]
@Chakroun-Anas  the config
![image](https://user-images.githubusercontent.com/3384734/63186941-fa93ea00-c05d-11e9-8645-9d714fd165bf.png)
Thanks

**Comment by Chakroun-Anas** [comment]
Hello @pookdeveloper,

The problem is not with the prefix, the detection failed because the usage of the backquote, i have just pushed a new version (1.2.31) that deal with this, please update the extension, test again and give me your feedback.

Thx

**Comment by pookdeveloper** [comment]
Thanks it works :)

**Comment by ismaelgomesesilva** [comment]
Yes, firstly congratulation for this amazing plugin. I have the same problem in version 2.1.7. Windows. Visual Studio 1.63.1

**Comment by alandouglas96** [comment]
Same here on Mac! Version 2.1.7. Visual Studio 1.63.2.

**Comment by auleki** [comment]
Facing the same error as well and using the command palette does nothing as well. But I can add logs and comment them

**Comment by vishantsehrawatradiansys** [comment]
Delete all functionality is not working for me , neither using shortcut or command palette, reinstalled, changed keybinding, still doesn't work. i 9 mackbook pro
