### ISSUE TITLE
Is this project still being maintain?

### ISSUE THREAD

**Issue by CircleOnCircles** [Chakroun-Anas/turbo-console-log#82]
I see no issue and pr being taking care of for months.

**Comment by Chakroun-Anas** [comment]
Hello,

Sorry for the passiveness during the last months, in fact i had a lot of things going on in my professional career, i'm coming back to maintain the extension like never before 🙂

Thx.

**Comment by CircleOnCircles** [comment]
There are a lot of pull requests waiting for review please take a look. 

There are forks of this project some are in the vscode marketplace.
![Screenshot 2020-02-17 at 9 49 09 AM](https://user-images.githubusercontent.com/8089231/74620220-ee066080-516a-11ea-8648-1e145ade6ec4.png)

If those PRs get merged and make some release it would be a nice update to users. ☺️

**Comment by Chakroun-Anas** [comment]
The most urgent actions for me is to add a static type checker (flow) and write tests that cover the different use cases so that we can add more functionalities with more confidence ^^

**Comment by Chakroun-Anas** [comment]
Flow is added to the project and now we have also integration tests which will make us fix existing bugs and publish new features with so much confidence ^^
