### ISSUE TITLE
[Feature Request] Add filename and code line prefix

### ISSUE THREAD

**Issue by rusakovic** [Chakroun-Anas/turbo-console-log#85]
Hello

THank you for your extension.
It will be great if you could add feature for such prefix:

**index.js**
```
1
2
3 const a = 'Hello'
4 console.log('file: index.js | Line 4 | a', a)
```

Thank you

**Comment by rusakovic** [comment]
Hello!

Is it possible to add this functionality?
Thank you

**Comment by Chakroun-Anas** [comment]
Hello, i'm so sorry for the late response but better late than never :)

I implemented this in the 2.1.0 version, please check and get back to me so that we can close this, thank you so much for your feedback.

**Comment by sghsri** [comment]
Can you make this an option in the settings to include, it is very annoying when all I want to be printed is the variable name. Thanks!

**Comment by Raju** [comment]
![image](https://user-images.githubusercontent.com/42042961/99915491-09218480-2d2a-11eb-9463-f7a147af4233.png)

looking good can we get option to overwrite few things or reorder them inside the log

**Comment by Chakroun-Anas** [comment]
@sghsri With the version 2.1.3 you can activate/deactivate this option via the extension settings (it's activated by default), please test this and get back to me so that we can close this issue.

@Raju You can open a new issue and i will look at it 🙂

**Comment by sghsri** [comment]
@Chakroun-Anas awesome thank you for getting back to me so quickly and adding it!

I was testing a little bit and noticed a big, it seems like when parsing class arrow functions the functionName in the log message isn't properly being parsed and is retaining the "=". Here's a picture of it:

![image](https://user-images.githubusercontent.com/13592854/99987581-427fe180-2d76-11eb-86fe-e33ccec5c897.png)

**Comment by chakroun-anas-contentsquare** [comment]
Hello, glad that we can close this issue, you are more than welcome to  open another  new issue for what you just mentioned, thanks.

**Comment by Chakroun-Anas** [comment]
Hello, glad that we can close this issue, you are more than welcome to open another new issue for what you just mentioned, thanks.
