### ISSUE TITLE
ctrl + alt +L  does nothing 

### ISSUE THREAD

**Issue by abhedindulkar** [Chakroun-Anas/turbo-console-log#93]
It just removes the variable and gives a dot at the place and as we use ctrl+alt +L the dot goes below to the previous dot 
![image](https://user-images.githubusercontent.com/43247545/84521292-67195d00-acf2-11ea-890e-642957f90d91.png)

**Comment by rohantarai** [comment]
@abhedindulkar 
after installing this extension.
- Edit this file `C:\Users\<Username>\AppData\Roaming\Code\User\keybindings.json`
- Add these json values in `keybindings.json`
```
  {
    "key": "alt+shift+l",
    "command": "turboConsoleLog.displayLogMessage"
  },
  {
    "key": "alt+shift+d",
    "command": "turboConsoleLog.deleteAllLogMessages"
  },
  {
    "key": "alt+shift+c",
    "command": "turboConsoleLog.commentAllLogMessages"
  },
  {
    "key": "alt+shift+u",
    "command": "turboConsoleLog.uncommentAllLogMessages"
  }
```
- Save and It will start working

**Comment by Fourie-r** [comment]
I have the same problem, ctrl+alt+l does nothing for me as well, but I also dont have such file keybindings.json in this directory. The only json file there is settings.json.

**Comment by rohantarai** [comment]
@Fourie-r if there is no keybindings.json file then you can create one there.

**Comment by alok722** [comment]
> 
> 
> @abhedindulkar
> after installing this extension.
> 
>     * Edit this file `C:\Users\<Username>\AppData\Roaming\Code\User\keybindings.json`
> 
>     * Add these json values in `keybindings.json`
> 
> 
> ```
> [
>   {
>     "key": "alt+shift+l",
>     "command": "turboConsoleLog.displayLogMessage"
>   },
>   {
>     "key": "alt+shift+d",
>     "command": "turboConsoleLog.deleteAllLogMessages"
>   },
>   {
>     "key": "alt+shift+c",
>     "command": "turboConsoleLog.commentAllLogMessages"
>   },
>   {
>     "key": "alt+shift+u",
>     "command": "turboConsoleLog.uncommentAllLogMessages"
>   }
> ]
> ```
> 
>     * Save and It will start working

Now, it works...
Thanks!
