### ISSUE TITLE
How to change the shortcut?

### ISSUE THREAD

**Issue by himat** [Chakroun-Anas/turbo-console-log#94]
I don't want to use ctrl + alt + L to log something. How do I change the default shortcut?

**Comment by selvakumardhivakar** [comment]
Go to your vscode keybindings settings! Ctrl + K Ctrl +S

search turbo console log or any shortcut change you want. You can edit there!

**Comment by pookdeveloper** [comment]
Go to keyboard shortcut and change it, in mac: commnad +k +s, in windows: control +k +s or:
![image](https://user-images.githubusercontent.com/3384734/90688021-197b1c80-e26e-11ea-9271-49ee646cc7f0.png)
