### ISSUE TITLE
The alt + shift + d shortcut exceeded it's power

### ISSUE THREAD

**Issue by Apawn1979** [Chakroun-Anas/turbo-console-log#95]
The shortcut removed all _console.log_ in the page even that is not added by Turbo Console Log.
That's not expected.

**Comment by Chakroun-Anas** [comment]
Hello,

Fixed with 2.1.0 version, please check and get back to me, thank you.

**Comment by Apawn1979** [comment]
Hi,
I'm sorry for writing back not timely.
It works! Thank you!

**Comment by flexbox** [comment]
Hey @Apawn1979 
If your problem is solved can you please close the issue 😉
