### ISSUE TITLE
This version"turboConsoleLog.insertEnclosingClass" and "turboConsoleLog.insertEnclosingFunction"doesn't work well

### ISSUE THREAD

**Issue by zhangbowen-github** [Chakroun-Anas/turbo-console-log#99]
This version"turboConsoleLog.insertEnclosingClass" and "turboConsoleLog.insertEnclosingFunction"doesn't work well

**Comment by chakroun-anas-contentsquare** [comment]
Hello,

Can you add more details please ?

Thx

**Comment by pookdeveloper** [comment]
I have the same issue I check to false and dosen't works

**Comment by pookdeveloper** [comment]
Hii when it will be fixed ? Thanks

**Comment by Chakroun-Anas** [comment]
I'm really sorry for the delay, i just went back to continue the journey. I just pushed a new version: 2.0.2 that fix this, please check and get back to me.

**Comment by pookdeveloper** [comment]
@Chakroun-Anas perfect !  Thanks to return back ! :)
